### ISSUE TITLE
Inconsistent Results from NSGA-II

### ISSUE THREAD

**Issue by khoopes** [Project-Platypus/Platypus#118]
Excuse my inexperience with things like this. I am working on a project where I am doing a single objective optimization of 7 variables with 4 constraints. Right now I am using NSGA-II. I use a population size of 480 and run for 500 generations.

My issue is that if I run this case multiple times I get different optimums which are different enough to have me worried that I have not found the global optimum. Is this just a sign that my population size isn't large enough and/or my number of generations isn't large enough?

In previous implementations of NSGA-II I have seen options for mutation scale, standard deviation of the random numbers generated, and shrink where the code will decrease the mutation range as the optimization progresses. Are there options like this in platypus? Or am I missing something similar?

Thanks,

**Comment by hh-wu** [comment]
I think you can use binary encoding instead of real encoding.

**Comment by khoopes** [comment]
I am not quite sure I know what you mean by that, can you elaborate?

Thanks,

**Comment by dhadka** [comment]
Hi @khoopes, there is no built-in mechanism to adjust the mutation range dynamically. however it should be possible with a little extra work.  For the default operators SBX and PM, you can narrow the variability in generated offspring by increasing the distribution_index.  Here's an example (please note that I have not tested this code, so you may need to tweak it to get it to work):

```
sbx = SBX()
pm = PM()
algorithm = NSGAII(problem, variator = GAOperator(sbx, pm))

for i in range(10):
    algorithm.run(1000)
    sbx.distribution_index *= 1.1
    pm.distribution_index *= 1.1
```

I would also suggest trying with a smaller population size and more generations.  Generally speaking, a larger population slows convergence because there is more genetic diversity, which requires more generations to converge.
