### ISSUE TITLE
Open discussions page for questions

### ISSUE THREAD

**Issue by EwoutH** [Project-Platypus/Platypus#220]
Would it be possible to enable the GitHub Discussions page for this repository? This way there is a central place for questions from users, without them having to open an issue.

See https://docs.github.com/en/discussions/quickstart

**Comment by FrancoisGLEYZON** [comment]
It would be very nice, thanks you @EwoutH ! 

Maybe it is then currently not the best location to ask it, but there is a small question (as I did not find any information in the documents or exemples) :

Is there a possibility, using platypus optimisation tool, to save or archive the non dominated points at each generation ? The goal is to be able to track the evolution of the Pareto front along the optimisation in order to have a visual representation of the convergence (or not) of the results. 

I really think that it has to do somthing with the "Archive" but given my tries, I was not able to find a way to use it succefully. I will continue to look for it but I would appreciate any tips or advise ;) Thanks !

![2024-01-17 09_40_25-Inbox - Francois Gleyzon@de ebmpapst com](https://github.com/Project-Platypus/Platypus/assets/95983493/f3012616-cd56-4187-8aba-bdc3a288bea7)

**Comment by dhadka** [comment]
@EwoutH Thanks for the suggestion!  Discussions are enabled.

@FrancoisGLEYZON Callback is the right approach.  See the following for an example: https://github.com/Project-Platypus/Platypus/blob/2c78f234f60cb3020512d55733eeaeed8cf289a2/examples/tsp.py#L36
