### ISSUE TITLE
How to define problem.types with specific Integers

### ISSUE THREAD

**Issue by ghost** [Project-Platypus/Platypus#29]
Hi,
I use the Platypus Project for the optimization of a off-grid PV-Battery System. My decision variabls are the PV Panel Power and Battery capacity installed.
I defined them as Integers in the following manner:

from platypus import NSGAII, Problem, Integer
int1 = Integer(80, 200)  
int2 = Integer(540, 1920)
problem.types[:] = [int1, int2] 

Is there now a way to define a step size inside the integer range of min and max values.
You can imagine that there ar not Pv module with 81W but only in a 10W step, meaning 80W, 90W,100W...
Sts just my first time using Python and Platypus.
Thanks for your help!
Fabian

**Comment by dhadka** [comment]
Hi, an easy way to handle step sizes like this is to scale the values by the step size.  For example, for a 10W step, divide the min/max bounds by 10:

    int1 = Integer(8, 20)

And convert back in your evaluate(x) method:

    value1 = x[0]*10

**Comment by fs1111** [comment]
thanks for your fast reply! So far I define my problem without using the problem class, because I faced problems to start the evaluator.
My code looks as follows (with two decision varibales, two objectives and 4 constraints), the MAIN function returns the two objectives and the four constraints:
` 
from platypus import NSGAII, Problem, Integer

problem = Problem(2, 2, 4)  
problem.directions[0] = Problem.MINIMIZE
problem.directions[1] = Problem.MINIMIZE
int1 = Integer(80, 200)
int2 = Integer(540, 1920)
problem.types[:] = [int1, int2] 
    
problem.constraints[0] = ">=0"
problem.constraints[1] = "<=0"
problem.constraints[2] = ">=0"
problem.constraints[3] = "<=0"
problem.function = MAIN             

algorithm = NSGAII(problem)
algorithm.run(1000)
`
Sorry but I am stucked to implemet your idea without the evaluator.
Thanks again for your support!
Fabian

**Comment by dhadka** [comment]
By evaluate(x), I mean the MAIN function in your example:

    problem.function = MAIN

I'm guessing you have something like:

    def MAIN(x):
        ...

This is where you would convert the values:

    def MAIN(x):
        value1 = x[0]*10
        ...

**Comment by fs1111** [comment]
Thanks a lot for your support. With this it works!
