### ISSUE TITLE
PBI result verification

### ISSUE THREAD

**Issue by dhadka** [Project-Platypus/Platypus#59]
Hey @eigeneko 

I made the necessary modifications so you can use PBI with MOEA/D.  From the image below, you can see that with PBI, it's converging to the three corners.  Can you please check if this is expected?

Is there a good default for theta?

```python

import functools
import matplotlib.pyplot as plt
from platypus import *
from mpl_toolkits.mplot3d import Axes3D

if __name__ == '__main__':
    problem = DTLZ2(3)
        
    algorithms = [(MOEAD, {}, "MOEAD (Chebyshev)"),
                  (MOEAD, {"scalarizing_function":functools.partial(pbi, theta=0.0)}, "MOEAD (PBI)")]
    
    with ProcessPoolEvaluator() as evaluator:
        results = experiment(algorithms, problem, seeds=1, nfe=10000, evaluator=evaluator)

    # display the results
    fig = plt.figure()
    
    for i, algorithm in enumerate(six.iterkeys(results)):
        result = results[algorithm]["DTLZ2"][0]
        
        ax = fig.add_subplot(1, 2, i+1, projection='3d')
        ax.scatter([s.objectives[0] for s in result],
                   [s.objectives[1] for s in result],
                   [s.objectives[2] for s in result])
        ax.set_title(algorithm)
        ax.set_xlim([0, 1.1])
        ax.set_ylim([0, 1.1])
        ax.set_zlim([0, 1.1])
        ax.view_init(elev=30.0, azim=15.0)
        ax.locator_params(nbins=4)
    
    plt.show()
```

![figure_1](https://user-images.githubusercontent.com/2496211/39887870-445fa0bc-5461-11e8-8ec8-8c1e793d5cde.png)

**Comment by eigeneko** [comment]
I think the PBI function can work for both maximization and minimization problem.  only a modification mentioned in 
**Li, H. and Zhang, Q. "Multiobjective Optimization problems with Complicated Pareto Sets, MOEA/D and NSGA-II." IEEE Transactions on Evolutionary Computation, 13(2):284-302, 2009**

Just because I see your original code in `weights.py/chebyshev`. There is no absolute value in
`objs[i]-ideal_point[i]`  so I think you maybe already assume that all problems is minimization.

btw, could you please tell me
- How should I specify the max or min for a problem ?
- When should I use `update_utility` in MOEAD ?
- How to specify theta using `functools.partial(pbi, theta=0.5)`
this original way doesn't work
```python
problem = DTLZ2()
algorithm = normal_pbi(problem, scalarizing_function=pbi)
algorithm.run(10000)
```
I hope more people can use Platypus and we could have a well organised document in the future !
