### ISSUE TITLE
Is it possible to use custom initial population? 

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [Project-Platypus/Platypus#62]
I have some good guess about the final PF, is it possible to add them into the initial population or archives?

**Comment by dhadka** [comment]
Try using [InjectedPopulation](https://github.com/Project-Platypus/Platypus/blob/d6aabe9bef6eca4087a26df8eca36406aacb9dac/platypus/operators.py#L41).  For example:

    algorithm = NSGAII(problem, generator = InjectedPopulation(init_pop))

I added this today, so please pull the latest changes from master.

**Comment by Alaya-in-Matrix** [comment]
Thanks!

**Comment by ecchapin** [comment]
Hi, 

Following on this previous comment, I am also interested in giving it a custom initial population.  Could you provide an example of how you write the code for init_pop.  For example, I have 14 binary decision variables.  How would I give platypus a couple of initial solutions with init_pop?   

Thanks so much, 
Emily

**Comment by kimbrerfesten** [comment]
Would also love an example of how to do this.
It would also support restarting the run.

**Comment by dieaquino** [comment]
Here's the example, this worked to me:
```
problem = Problem(14,2)
problem.types[:] = [Integer(4, 32),        
                    Integer(4, 32),        
                    Integer(1, 4),         
                    Integer(1, 5),         
                    Integer(0, 3),         
                    Integer(4, 32),        
                    Integer(4, 32),        
                    Integer(1, 4),         
                    Integer(1, 5),         
                    Integer(0, 3),         
                    Integer(4, 32),        
                    Integer(4, 32),
                    Integer(1, 4),
                    Integer(1, 5)]
problem.function = my_function
problem.directions[:] = Problem.MAXIMIZE

v_population_size = 5
init_pop = [Solution(problem) for i in range(v_population_size)]
pop_indiv = [[x.rand() for x in problem.types] for i in range(v_population_size)]

for i in range(v_population_size):
    init_pop[i].variables = pop_indiv[i]
	
algorithm = NSGAII(problem, population_size=v_population_size, generator=InjectedPopulation(init_pop))
algorithm.run(10)   


```

**Comment by ashuein** [comment]
> Here's the example, this worked to me:
> 
> ```
> problem = Problem(14,2)
> problem.types[:] = [Integer(4, 32),        
>                     Integer(4, 32),        
>                     Integer(1, 4),         
>                     Integer(1, 5),         
>                     Integer(0, 3),         
>                     Integer(4, 32),        
>                     Integer(4, 32),        
>                     Integer(1, 4),         
>                     Integer(1, 5),         
>                     Integer(0, 3),         
>                     Integer(4, 32),        
>                     Integer(4, 32),
>                     Integer(1, 4),
>                     Integer(1, 5)]
> problem.function = my_function
> problem.directions[:] = Problem.MAXIMIZE
> 
> v_population_size = 5
> init_pop = [Solution(problem) for i in range(v_population_size)]
> pop_indiv = [[x.rand() for x in problem.types] for i in range(v_population_size)]
> 
> for i in range(v_population_size):
>     init_pop[i].variables = pop_indiv[i]
> 	
> algorithm = NSGAII(problem, population_size=v_population_size, generator=InjectedPopulation(init_pop))
> algorithm.run(10)   
> ```

can you elaborate a little bit on what your code is actually doing?

**Comment by joergfelder** [comment]
Thanks for the example code. I am currently running an optimization where each evaluation takes really long (a 3D EM problem) so that I store the variables and results in a csv file as a precaution. This turns out to be a good idea, as the computer was shut down due to a power failure last week. No I am looking into restarting the optimization. 
I am ok with the code above. However, in the meantime I have more results that my population size is large. So ideally, I would like to inject only the best solutions up to now. However, since I am optimizing for five 5 different target functions I am not quite sure how to select the "best"solutions. Can I use the nondominated function for this?

**Comment by joergfelder** [comment]
My current implementation is as follows. I read the results from previous runs from a cdv file:

` 
# open result file for reading
 file = open( str(CSVFileName), 'r')
 csvreader = csv.reader(file)
    
# read rows from cdv file 
for row in csvreader:
     if len(row) != 0:
         Variable_1 = np.append(Variable_1, float(row[0]))
         Variable_2 = np.append(Variable_2, float(row[1]))
       ...
        Result_1 = np.append(Variable_1, float(row[X]))
        Result_2 = np.append(Variable_2, float(row[X+1]))
  
 # close csv file
 file.close()
    

# assign solutions    
init_pop = [Solution(problem) for i in range(len(Result_1))]
for i in range(len(Result_1)):
    init_pop[i].variables = [ Variable_1, Variable_2, ...]
    init_pop[i].objectives = [ Result_1, Result_2 ...
    init_pop[i].constraints = [ Constraint_1, Constraint_2, ... ] 
   # because I only store results that do not violate constraints
    init_pop[i].constraint_violation = 0.0
    init_pop[i].feasible = True
    init_pop[i].evaluated = True
        
# keep only the non-dominated solutions
nondominated_solutions = nondominated(init_pop)
NumberOfIterations = len(Result_1)
    
# set desired number of iterations
i_num_evals = 500

# dump precomputed results into the algorithm initialisation
# Note I use the number of non dominated solutions from previous runs as the population size for sake of simplicity
algorithm = NSGAII(problem, population_size=len(nondominated_solutions), generator=InjectedPopulation(nond_sols))
 
# compute remaining number of iterations for execution of the algorithm  
i_num_evals = i_num_evals - NumberOfIterations + len(nondominated_solutions)

# run optimization
algorithm.run(i_num_evals)
`

I hope that this works out. If anybody has some hints on improving the code I am more than happy to hear those.
