### ISSUE TITLE
Interrupting an optimization run

### ISSUE THREAD

**Issue by infinity77** [Project-Platypus/Platypus#78]
Sorry for opening an issue, I didn’t know where to post to ask a question. I have setup an optimization run with Platypus in my user interface, and the user can choose the maximum number of function evaluations to perform.

That said, the objective function takes a while to evaluate - sometimes several minutes, and the user can get bored to wait and would like to interrupt the optimization. I have no problem in keeping the GUI responsive to leave the user the choice of hitting the “stop” button, but I have no idea how to stop the Platypus optimization run.

Does anyone know what I may try?

Thank you in advance for your suggestions.

Andrea.

**Comment by dhadka** [comment]
There is no built-in support, but here are a few thoughts:

1. Stop at the completion of an iteration - Subclass `TerminationCondition` to provide a version that is cancellable.  If the population size is large (N), it could take a long time to stop (N * FuncEvalTime).

2. Hacky - This simplest way without modifying a lot of code would be to check a cancellation flag in your evaluation function and raise an error.  This will cause the algorithm to exit the run(...) method, where you can catch this error.  You will lose any evaluations performed in the current iteration, but can get the last-saved approximation set in `algorithm.result`.

3. Ideal - Add a cancellation flag to the Algorithm, which is checked before/after each function evaluation.  If cancelled, safely terminate the algorithm and return the latest result.  This would require the most work since there are potentially a lot of places that need to be updated.

**Comment by infinity77** [comment]
Thanks David, I’ll give approach (2) a try - seems the simplest and quickest to implement.
