### ISSUE TITLE
Importance adjustment

### ISSUE THREAD

**Issue by kichinosukey** [Project-Platypus/Platypus#86]
How can I adjust importance of objectives? Is the order of objective function like below?

If x**2 is important.
`
def shaffer(x):
    return x**2, (x-2)**2
`
elif (x-2)**2 important
`
def shaffer(x):
    return (x-2)**2, x**2
`

**Comment by dhadka** [comment]
Platypus uses Pareto dominance by default, so all objectives are treated as equally important.  The order should not matter.

Trying to assign importance to each objective is not trivial.  For example, do you want to minimize `x**2` always and only use `(x-2)**2` as a tie-breaker?  If so, you will want to use "lexicographical ordering" instead of Pareto dominance.  Platypus does not support lexicographical ordering, however.

You can scale the objectives, such as ```def shaffer(x): return x**2 + ((x-2)**2)/k``` where k is some value >= 1.  The larger you make k, the less important the second term becomes.

**Comment by kichinosukey** [comment]
Latter way is better and easy for me.
I have used this library in this month. It is very useful and helps me.

Thanks a lot.
